### ISSUE TITLE
Diagnostics svrl:text tags missing

### ISSUE THREAD

**Issue by rjelliffe** [Schematron/schematron#26]
I have not verified this. It is from a 2012 email. - Rick.

Radu Cernuta reported a bug and provided a fix, that the diagnostics were not getting the text.

iso-svrl-for-xslt1.xsl  2010 version line 410
iso-svrl-for-xslt2.xsl  2010 version line 425

	

		 
		<svrl:text>
			<xsl:apply-templates mode="text" />
		</svrl:text>
		

	</svrl:diagnostic-reference>

**Comment by tgraham-antenna** [comment]
All six `<svrl:text>` in current code have `<xsl:apply-templates mode="text" />`.
