### ISSUE TITLE
Move 'ant-schematron' to separate repository

### ISSUE THREAD

**Issue by tgraham-antenna** [Schematron/schematron#33]
`ant-schematron` should be moved to a separate repository under the Schematron organisation.

Subversion lets you checkout part of a project -- e.g., just the `ant-schematron` part -- but Git doesn't.  OTOH, Git, like Subversion, lets you have external submodules.

It would be cleaner if `ant-schematron` was in a separate repository that, if necessary, included the XSLT implementation as a submodule.

https://github.com/webb/schematron-impl, for example, is a fork of this repository where everything other than the XSLT implementation has been removed.  This repository should end up like that.

**Comment by rjelliffe** [comment]
Yes, good idea

**Comment by tgraham-antenna** [comment]
Done, but the project needs a build file, or similar, for building the jar.  See Schematron/ant-schematron#1.
