### ISSUE TITLE
ant-schematron and XSLT2

### ISSUE THREAD

**Issue by xephon2** [Schematron/schematron#35]
Hi,

I only found a version of `ant-schematron.jar` from 2011, it's probably outdated, but I could not find a newer release on Github or Maven Central.

I develop a DITA-OT plugin with schematron validation, but I get the following fail when publishing:

```
schematron:
[schematron] Fail: This implementation of ISO Schematron does not work with
[schematron]    schemas using the "xslt2" query language.
[schematron] Processing terminated by xsl:message at line 567 in iso_schematron_skeleton_for_xslt1.xsl
```

I assume, that this is a problem of my old *jar*. Could you please create a release here or tell me, where I can download the latest version or, if it is a bug in my script, what I'm doing wrong?

Thanks a lot

**Comment by metju30** [comment]
Did you get the right .jar? Where? Can you send it to me or make availabe for download?
Thx!

**Comment by xephon2** [comment]
@metju30 I did not get a jar, but now I'm using [phax/ph-schematron](https://github.com/phax/ph-schematron).
