### ISSUE TITLE
document-uri()  problem in XSLT1 schema when generated by XSLT2 engine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Schematron/schematron#4]
```
Lars Hutter has reported the old problem of stylesheet versions caused some 
problem. See discussion at 
http://www.eccnet.com/pipermail/schematron/2010-July/000295.html   

There are two problems:

1) Should @queryBinding="xslt2" cause a stylesheet with @version="2.0". 

According the draft ISO standard binding for XSLT2, backward compatibility 
should be false. See Annex L, http://www.itscj.ipsj.or.jp/sc34/open/1419.pdf So 
that suggests that certainly 2.0 should be generated. (Need to check it is.)

2) The svrl for saxon script generates  document-uri() function even for 
@queryLanguage="XSLT1" schemas. This is good for people then running the XSLT1 
script on SAXON: it allows better reporting, but will fail on XSLT1 systems.  
Sometimes people cross-compile, for example when the compiled stylesheet will 
run on IE attached to an XHTML document. 

At the moment there is some source code comment to delete document-uri(), but 
this requires hacking which we need to get beyond, even if it is an edge-case. 

Need to figure out better system: a command-line switch is one more thing to 
think about?, some use of xsl:fallback maybe?, or what?
```

Original issue reported on code.google.com by `jellif...@gmail.com` on 10 Jul 2010 at 5:01

**Comment by rjelliffe** [comment]
> 1) Should @queryBinding="xslt2" cause a stylesheet with @version="2.0"?

Yes.  I have checked that the iso_svrl_for_saxon.xsl does generate version="2.0".  I have checked that iso_svrl_for_xslt1.xsl generates version="1.0" as expected.


>   2) The svrl for saxon script generates  document-uri() function even for 
@queryLanguage="XSLT1" schemas.

Yes.  iso:schema/@queryBinding  sets what language used in the rule/@context, assert/@test, le1t/@select and so on.   But the compiler can generate scripts of any language that is compatible with that. XSLT2 is a superset of XSLT1 as far as the XPath is concerned;  so we can generate XSLT2 code (and take advantage of extra functiontlity like document-uri() in the Xpaths that do not come in from the original scripts.

If you want to cross-compile to run on systems that only support XSLT1, then you need to use iso_svrl_for_xslt1  to compile.   

(If you can show examples where an Schematron XPath in XSLT1 will have a different effect in XSLT2, then that would indeed be a problem that needs to be fixed, but I am not aware of an actual problem. )
